lr: 0.00001
batch_size: 10
model_name: weakloc
pretrained_ckpt: false
feature_size: 2048
num_class: 20
dataset_name: Thumos14reduced
max_seqlen: 1200
Lambda: 0.5
num_similar: 3
seed: 1
max_iter: 50000
feature_type: UNT
print_every: 100
